name: mhu_flutter_commons
description: Commons utilities used in my Flutter projects
version: 1.0.4
repository: https://github.com/maprohu/mhu_flutter_commons

environment:
  sdk: ^3.0.5

dependency_overrides:
  mhu_dart_commons:
    path: ../mhu_dart_commons
  mhu_dart_proto:
    path: ../mhu_dart_proto
  mhu_dart_model:
    path: ../mhu_dart_model
  mhu_dart_builder:
    path: ../mhu_dart_builder

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  intl: ^0.18.1
  collection: ^1.17.1
  logger: ^1.4.0
  go_router: ^9.0.3
  flutter_svg:  ^2.0.7
  image:  ^4.0.17
  fast_immutable_collections: ^9.1.5
  isar: ^3.1.0+1
  decimal: ^2.3.3

  mhu_dart_commons: ^1.0.7
  mhu_dart_model: ^1.0.1
  mhu_dart_proto: ^1.0.1
  protobuf: ^3.0.0
  flutter_colorpicker: ^1.0.3
  recase: ^4.1.0
  fixnum: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  mhu_dart_builder: ^1.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
