name: mhu_flutter_commons
description: Commons utilities used in my Flutter projects
version: 1.0.0-dev

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  intl: ^0.18.1
  collection: ^1.17.1
  mhu_dart_commons: ^1.0.5
#  mhu_dart_commons:
#    path: ../mhu_dart_commons

dev_dependencies:
  flutter_test:
    sdk: flutter
